Repository mej/nhc, pull requests merged in 2022-12, with the labels that each got.

#114 Add csc_nvidia_smi.nhc to Makefile to get into RPM
  Makefile.am
Labels: bug, packaging

#115 Numerous improvements to Slurm reboot handling and planned node state
  helpers/node-mark-offline
  helpers/node-mark-online
Labels: enhancement

#117 Fix unsafe string array conversion for passwd file parsing
  scripts/common.nhc
Labels: bug, enhancement
